### ISSUE TITLE
Determine possible issues before swap is initiated (i.e. amounts too low for swap)

### ISSUE THREAD

**Issue by nathanielwood** [go-faast/faast-web#12]
By actively fetching the swap fee while the assets are being "modified", the app can determine whether the amounts will be enough to proceed before clicking "save".

**Comment by rraallvv** [comment]
Is this an issue related to TUSD tokens?

I'm asking because I tried to swap 5 USD worth of ETH to TUSD but the swap failed. The transaction went through but I didn't receive any tokens.

By the way, is the support@faa.st address working or do it need to be updated, since I've sent several emails asking what could be the problem but haven't received yet any response. Not even an automatic one.

**Comment by rraallvv** [comment]
This is what I see in the details:
![screen shot 2018-07-14 at 9 42 40 am](https://user-images.githubusercontent.com/1840524/42724989-c0efcd2a-874a-11e8-8ea7-59118fdc6e54.png)

**Comment by rraallvv** [comment]
This is what I see in the details:
![screen shot 2018-07-14 at 9 42 40 am](https://user-images.githubusercontent.com/1840524/42724989-c0efcd2a-874a-11e8-8ea7-59118fdc6e54.png)

**Comment by moeadham** [comment]
@rraallvv This was a backend issue. Support has reached out.

**Comment by rraallvv** [comment]
Indeed @moeadham, the issue was solved. They did a wonderful job in solving the problem. I highly recommend Faast for crypto and token swaps and exchanges.
